[package]
name = "ociarchive2disk"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
oci-distribution = "=0.11.0"
tokio = { version = "1", features = ["full"] }
envy = "0.4.2"
serde = "1.0.204"
new_mime_guess = "4.0.1"
zstd = "0.13.2"
tar = "0.4.41"
