name: Release
on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        action: [ociarchive2disk]
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t ghcr.io/${{ github.repository }}/${{ matrix.action }} -f ${{ matrix.action }}/Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push ${{ matrix.action }} action image
        run: docker push ghcr.io/${{ github.repository }}/${{ matrix.action }}
